name: yust
description: Build awesome apps with Flutter and Firebase.
version: 1.8.3
homepage: https://github.com/janneskoehler/yust

environment:
  sdk: ">=2.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.1.1
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0
  cloud_firestore: ^1.0.0
  firebase_storage: ^8.0.0

  provider: ^5.0.0
  intl: ^0.17.0
  shared_preferences: ^2.0.3
  progress_dialog: ^1.2.0
  collection: ^1.14.13
  package_info: ^2.0.0
  image_picker: ^0.7.2
  photo_view: ^0.10.2
  file_picker: ^3.0.0
  mime: ^1.0.0
  url_launcher: ^6.0.2
  http: ^0.13.0
  image: ^3.0.1
  flutter_native_image: ^0.0.5+3
  path_provider: ^2.0.1
  connectivity: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.1.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
