name: yust
description: Build awesome apps with Flutter and Firebase - this package allows communication with Firebase to be a breeze.
version: 3.29.6
homepage: https://github.com/univelop/yust

environment:
    sdk: '>=3.8.0 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    cloud_firestore: ^6.0.0
    collection: ^1.19.1
    coordinate_converter: ^1.2.3
    firebase_auth: ^6.0.1
    firebase_core: ^4.0.0
    firebase_storage: ^13.0.0
    googleapis_auth: ^2.0.0
    googleapis: ^14.0.0
    http: ^1.5.0
    intl: ^0.20.2
    json_annotation: ^4.9.0
    mime: ^2.0.0
    timezone: ^0.10.1
    uuid: ^4.5.1
    meta: '>=1.15.0 <2.0.0'
    dart_jsonwebtoken: ^3.2.0

dev_dependencies:
    build_runner: ^2.2.0
    flutter_lints: ^6.0.0
    json_serializable: 6.9.5
    test: ^1.25.15
