name: yust
description: Build awesome apps with Flutter and Firebase.
version: 3.0.0-dev.5
homepage: https://github.com/janneskoehler/yust

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  firebase_storage: ^10.2.6

  provider: ^6.0.2
  intl: ^0.17.0
  shared_preferences: ^2.0.3
  share_plus: ^3.0.4
  flutter_easyloading: ^3.0.0
  collection: ^1.15.0
  image_picker: ^0.8.4
  photo_view: ^0.12.0
  file_picker: ^4.2.3
  mime: ^1.0.0
  url_launcher: ^6.0.2
  http: ^0.13.0
  image: ^3.0.1
  dio: ^4.0.0
  flutter_native_image: ^0.0.5+3
  path_provider: ^2.0.1
  connectivity_plus: ^1.0.6
  mask_text_input_formatter: ^2.0.0
  open_file: ^3.0.3
  paginate_firestore: ^1.0.3
  universal_html: ^2.0.8
  firebase_storage_mocks: ^0.5.0
  fake_cloud_firestore: ^1.1.3
  firebase_auth_mocks: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  json_serializable: ^6.1.4

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
